[[diffutils]]
arch = "aarch64"
git-tree-sha1 = "7dda6b3c64e4d10566a31cb2a31c0d4b419c827d"
os = "macos"

    [[diffutils.download]]
    sha256 = "034014997f5f4e4662225efb5fcdf7387c66342498feec49165e12eca2688114"
    url = "https://github.com/JuliaBinaryWrappers/diffutils_jll.jl/releases/download/diffutils-v3.10.0+0/diffutils.v3.10.0.aarch64-apple-darwin.tar.gz"
[[diffutils]]
arch = "aarch64"
git-tree-sha1 = "f4b4ab16212647ef8dcc5e13d7bdcd069b0f25d8"
libc = "glibc"
os = "linux"

    [[diffutils.download]]
    sha256 = "c26fca586b1a00ffb6963f1351e927742970fb1d30296a3f5819d92a37e42f99"
    url = "https://github.com/JuliaBinaryWrappers/diffutils_jll.jl/releases/download/diffutils-v3.10.0+0/diffutils.v3.10.0.aarch64-linux-gnu.tar.gz"
[[diffutils]]
arch = "aarch64"
git-tree-sha1 = "35bf4b2e60701efc70d8775cc9b39191dd581169"
libc = "musl"
os = "linux"

    [[diffutils.download]]
    sha256 = "aadb3282e33a81a4ce049737ab4428c74ec732eb96956519d103371237dcdea6"
    url = "https://github.com/JuliaBinaryWrappers/diffutils_jll.jl/releases/download/diffutils-v3.10.0+0/diffutils.v3.10.0.aarch64-linux-musl.tar.gz"
[[diffutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4f9e3ef1e14ecbecd57e727228a5054a67cd3d1e"
libc = "glibc"
os = "linux"

    [[diffutils.download]]
    sha256 = "94cf6ee76fa53585952bdb9b15ba54f119d61449e54dae590772a21885e5ab32"
    url = "https://github.com/JuliaBinaryWrappers/diffutils_jll.jl/releases/download/diffutils-v3.10.0+0/diffutils.v3.10.0.armv6l-linux-gnueabihf.tar.gz"
[[diffutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dc35acbcb8191e4f23c457bc43bdaae096c21134"
libc = "musl"
os = "linux"

    [[diffutils.download]]
    sha256 = "fe056a8caf0ba745ca85babb3f309dfdca56502ffda30ed00365d61d8a1d6e57"
    url = "https://github.com/JuliaBinaryWrappers/diffutils_jll.jl/releases/download/diffutils-v3.10.0+0/diffutils.v3.10.0.armv6l-linux-musleabihf.tar.gz"
[[diffutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "343b7059d52aff6d303a006ec1572afb79d5e7ce"
libc = "glibc"
os = "linux"

    [[diffutils.download]]
    sha256 = "8d54aff0045a72eae531d35436221e26ad3fc4017199091dcc1a1c7404abc61d"
    url = "https://github.com/JuliaBinaryWrappers/diffutils_jll.jl/releases/download/diffutils-v3.10.0+0/diffutils.v3.10.0.armv7l-linux-gnueabihf.tar.gz"
[[diffutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b2a457caca4e87a27b364cfdde059a00cdf1a757"
libc = "musl"
os = "linux"

    [[diffutils.download]]
    sha256 = "71478ca4138d159d24d38245f6603a61c826439e40f31d466699847d2c80c1e0"
    url = "https://github.com/JuliaBinaryWrappers/diffutils_jll.jl/releases/download/diffutils-v3.10.0+0/diffutils.v3.10.0.armv7l-linux-musleabihf.tar.gz"
[[diffutils]]
arch = "i686"
git-tree-sha1 = "24eda8c06d9f6eee2aad39c7869314236c2c803f"
libc = "glibc"
os = "linux"

    [[diffutils.download]]
    sha256 = "937fb2a25089f4a100273f904194fe35e8a41bcfd6f2098d447c3dd93b281f28"
    url = "https://github.com/JuliaBinaryWrappers/diffutils_jll.jl/releases/download/diffutils-v3.10.0+0/diffutils.v3.10.0.i686-linux-gnu.tar.gz"
[[diffutils]]
arch = "i686"
git-tree-sha1 = "deb97bd430c97cc6553417f9232eb5b416d9fc73"
libc = "musl"
os = "linux"

    [[diffutils.download]]
    sha256 = "117087f4137ae0582565378a1834b37aae170d7364ec5d08039fdf28751d971a"
    url = "https://github.com/JuliaBinaryWrappers/diffutils_jll.jl/releases/download/diffutils-v3.10.0+0/diffutils.v3.10.0.i686-linux-musl.tar.gz"
[[diffutils]]
arch = "i686"
git-tree-sha1 = "cb72aa7f450527c037f3a5842a9b87fd8fe7cefb"
os = "windows"

    [[diffutils.download]]
    sha256 = "a2d21b1d52e35550c0f4e48f7e4984fc1bece358470e42d52c4605a41921b818"
    url = "https://github.com/JuliaBinaryWrappers/diffutils_jll.jl/releases/download/diffutils-v3.10.0+0/diffutils.v3.10.0.i686-w64-mingw32.tar.gz"
[[diffutils]]
arch = "powerpc64le"
git-tree-sha1 = "cffab6979a0b40ae317f603dd9b41160ce26a305"
libc = "glibc"
os = "linux"

    [[diffutils.download]]
    sha256 = "ce1d566bc1117a1f18e8d86f616e36732e3e96a7751215006cee73293ff0d6ae"
    url = "https://github.com/JuliaBinaryWrappers/diffutils_jll.jl/releases/download/diffutils-v3.10.0+0/diffutils.v3.10.0.powerpc64le-linux-gnu.tar.gz"
[[diffutils]]
arch = "x86_64"
git-tree-sha1 = "290ad1ecb775cfcd1612041d206f3a24e198d76b"
os = "macos"

    [[diffutils.download]]
    sha256 = "9d9a415de022ae14edfae39eb5a5706e77653420fa8a600067941ad3a29b5614"
    url = "https://github.com/JuliaBinaryWrappers/diffutils_jll.jl/releases/download/diffutils-v3.10.0+0/diffutils.v3.10.0.x86_64-apple-darwin.tar.gz"
[[diffutils]]
arch = "x86_64"
git-tree-sha1 = "5daa8b86cd11b88a5f594d92b112afee9498060a"
libc = "glibc"
os = "linux"

    [[diffutils.download]]
    sha256 = "2c402d8554348f2230f9f703a09291aa68bba2a2d08ee628773e80b46d62ac53"
    url = "https://github.com/JuliaBinaryWrappers/diffutils_jll.jl/releases/download/diffutils-v3.10.0+0/diffutils.v3.10.0.x86_64-linux-gnu.tar.gz"
[[diffutils]]
arch = "x86_64"
git-tree-sha1 = "869a71f9ff56cac2687da571ad199a8e6de833db"
libc = "musl"
os = "linux"

    [[diffutils.download]]
    sha256 = "22c20ad01119cef1a7325e634ed49d43a59011730d3ac3dede354a2cb16f1527"
    url = "https://github.com/JuliaBinaryWrappers/diffutils_jll.jl/releases/download/diffutils-v3.10.0+0/diffutils.v3.10.0.x86_64-linux-musl.tar.gz"
[[diffutils]]
arch = "x86_64"
git-tree-sha1 = "9a8f191c315dc8c1b609c8f90fcd6363f7f121a3"
os = "freebsd"

    [[diffutils.download]]
    sha256 = "f94972cc8df16fabc22a1b68f620e1490a9cd1ce569bd5fb912483674230446b"
    url = "https://github.com/JuliaBinaryWrappers/diffutils_jll.jl/releases/download/diffutils-v3.10.0+0/diffutils.v3.10.0.x86_64-unknown-freebsd.tar.gz"
[[diffutils]]
arch = "x86_64"
git-tree-sha1 = "0ae5b7a8b1573a5d38fc1b8c4f33e1527993702c"
os = "windows"

    [[diffutils.download]]
    sha256 = "6e6a551d4f5aabb8d70d4bbc677b07872f177b3e977e833427a3eb90cc70eb96"
    url = "https://github.com/JuliaBinaryWrappers/diffutils_jll.jl/releases/download/diffutils-v3.10.0+0/diffutils.v3.10.0.x86_64-w64-mingw32.tar.gz"
